#!/usr/bin/env python3
"""Bundle src/**/*.lua into a single dist/MaUI.lua (usable with loadstring).

Every module is wrapped in a function that receives a local `require`:
    require("Core/Util")  ->  module src/Core/Util.lua
Modules are loaded lazily and cached.

Usage : python3 build.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "src"
OUT = ROOT / "dist" / "MaUI.lua"

HEADER = """-- MaUI {version} -- generated by build.py, do not edit by hand.
-- Modular sources live in src/. Usage:
--   local MaUI = loadstring(readfile("MaUI.lua"))()   -- or via HttpGet
--   local ui = MaUI.new()
local __defs, __cache = {{}}, {{}}

local function __require(name)
	local cached = __cache[name]
	if cached ~= nil then
		return cached
	end
	local definition = __defs[name]
	if not definition then
		error("[MaUI] module not found : " .. tostring(name), 2)
	end
	local result = definition(__require)
	if result == nil then
		result = true
	end
	__cache[name] = result
	return result
end
"""


def module_name(path: Path) -> str:
    return path.relative_to(SRC).with_suffix("").as_posix()


def read_version() -> str:
    for line in (SRC / "init.lua").read_text(encoding="utf-8").splitlines():
        if line.startswith("MaUI.Version"):
            return line.split("=", 1)[1].strip().strip('"')
    return "dev"


def main() -> None:
    files = sorted(SRC.rglob("*.lua"))
    parts = [HEADER.format(version=read_version())]
    for path in files:
        name = module_name(path)
        body = path.read_text(encoding="utf-8").rstrip() + "\n"
        parts.append(f'\n__defs["{name}"] = function(require)\n{body}end\n')
    parts.append('\nreturn __require("init")\n')
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("".join(parts), encoding="utf-8")
    size = OUT.stat().st_size
    print(f"{len(files)} modules -> {OUT.relative_to(ROOT)} ({size / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
