local MaUI = H.loadLibrary()
T.section("Shell: smoke")
local ui = H.newLibrary(MaUI)
local window = ui:CreateWindow({ Title = "Hub", Version = "v1" })
local tab = window:AddTab({ Name = "Main", Icon = "home" })
local card = tab:AddSection({ Name = "Card", Icon = "bolt" })
card:AddToggle({ Name = "T", Flag = "t" })
tab:AddToggle({ Name = "Loose" })
local cols = tab:AddColumns(2)
cols[1]:AddSection("A")
local sub = tab:AddSubTabs()
sub:AddTab("One"):AddSection("X")
window:SelectTab(tab)
T.check("builds", window.CurrentTab == tab)
