local MaUI = H.loadLibrary()
local function find(root, name) return M.find(root, name) end
local function buttons(root, label)
	for _, d in ipairs(root:GetDescendants()) do
		if d.ClassName == "TextButton" and d.Name == label then return d end
	end
end

T.section("Theme library API")
do
	local ui = H.newLibrary(MaUI)
	T.check("the default theme is Sakura", ui.Theme.Name == "Sakura")
	T.check("List includes presets", #ui.Theme:List() >= 3)
	ui.Theme:SetToken("Accent", Color3.fromRGB(1, 2, 3))
	T.check("SaveTheme stores the live edit and selects the theme", ui:SaveTheme("Mine") == true and ui.Theme.Name == "Mine")
	T.check("saved theme is listed", ui:ListThemes()[1] == "Mine")
	ui:SetTheme("Dark")
	T.check("LoadTheme restores colors", ui:LoadTheme("Mine") and M.sameColor(ui.Theme:Get("Accent"), Color3.fromRGB(1, 2, 3)))
	T.check("invalid names are refused", ui:SaveTheme("///") == false)
	T.check("missing theme reports an error", select(2, ui:LoadTheme("Ghost")) == "no theme named Ghost")
	ui:SetDefaultTheme("Mine")
	T.check("default theme round trip", ui:GetDefaultTheme() == "Mine")
	local ui2 = H.newLibrary(MaUI, { ConfigFolder = ui.ConfigFolder })
	T.check("a new library starts with the saved default", ui2.Theme.Name == "Mine")
	T.check("DeleteTheme removes it and the default", ui2:DeleteTheme("Mine") and ui2:GetDefaultTheme() == nil and #ui2:ListThemes() == 0)
	M.files[ui.ConfigFolder .. "/themes/Bad.json"] = "{not json"
	T.check("a corrupted theme file is rejected", select(1, ui:LoadTheme("Bad")) == false)
end

T.section("Config library API")
do
	local ui = H.newLibrary(MaUI)
	local card = ui:CreateWindow({ Title = "W" }):AddTab("T"):AddSection("S")
	local toggle = card:AddToggle({ Name = "t", Flag = "t", Default = false })
	local slider = card:AddSlider({ Name = "s", Flag = "s", Min = 0, Max = 10, Default = 2 })
	toggle:Set(true); slider:Set(8)
	T.check("save + list", ui:SaveConfig("a") and ui:ListConfigs()[1] == "a")
	T.check("rename moves the file", ui:RenameConfig("a", "b") and ui:ListConfigs()[1] == "b" and ui.ConfigName == "b")
	T.check("renaming to an existing name fails", ui:SaveConfig("c") and ui:RenameConfig("b", "c") == false)
	T.check("renaming a missing config fails", ui:RenameConfig("zzz", "y") == false)
	T.check("ResetConfig restores defaults", ui:ResetConfig() == 2 and toggle:Get() == false and slider:Get() == 2)
	T.check("autoload set/get", ui:SetAutoload("b") and ui:GetAutoload() == "b")
	T.check("LoadAutoload applies it", ui:LoadAutoload() and toggle:Get() == true and slider:Get() == 8)
	T.check("renaming the autoload config keeps it", ui:RenameConfig("b", "d") and ui:GetAutoload() == "d")
	ui:SetAutoload(nil)
	T.check("clear autoload", ui:GetAutoload() == nil and select(2, ui:LoadAutoload()) == "no autoload configured")
	local code = ui:ExportConfig()
	T.check("export is a MAUI1 code", code:sub(1, 6) == "MAUI1:")
	toggle:Set(false, true); slider:Set(1, true)
	T.check("import applies the code", ui:ImportConfig(code) and toggle:Get() == true and slider:Get() == 8)
	T.check("garbage code rejected", ui:ImportConfig("hello") == false and ui:ImportConfig("MAUI1:{oops") == false and toggle:Get() == true)
	T.check("non-string code rejected", ui:ImportConfig(nil) == false)
end

T.section("ThemeEditor and ConfigManager components")
do
	local ui = H.newLibrary(MaUI)
	local window = ui:CreateWindow({ Title = "W" })
	local tab = window:AddTab("Settings")
	local editor = tab:AddThemeEditor({ Title = "Theme" })
	T.check("theme editor builds one picker per default token", find(editor.Frame, "Accent") ~= nil and find(editor.Frame, "Muted") ~= nil)
	local before = ui.Theme:Get("Accent")
	editor.Pickers.Accent:Set(Color3.fromRGB(10, 20, 30))
	T.check("picking a color previews it live on the theme", M.sameColor(ui.Theme:Get("Accent"), Color3.fromRGB(10, 20, 30)))
	ui:SetTheme("Dark")
	T.check("a theme change refreshes the pickers", M.sameColor(editor.Pickers.Accent:Get(), ui.Theme:Get("Accent")))
	editor.NameBox:Set("Custom", true)
	H.click(buttons(editor.Frame, "Save"))
	T.check("Save button stores a theme", ui:ListThemes()[1] == "Custom")
	H.click(buttons(editor.Frame, "Set default"))
	T.check("Set default button", ui:GetDefaultTheme() == "Custom")
	local custom = tab:AddConfigManager({ Title = "Configs" })
	custom.NameBox:Set("one", true)
	H.click(buttons(custom.Frame, "Create"))
	T.check("Create saves the config", ui:ListConfigs()[1] == "one")
	custom.List:Set("one", true)
	H.click(buttons(custom.Frame, "Set autoload"))
	T.check("Set autoload button", ui:GetAutoload() == "one")
	H.click(buttons(custom.Frame, "Delete"))
	T.check("Delete needs a second click", ui:ListConfigs()[1] == "one")
	H.click(buttons(custom.Frame, "Delete"))
	T.check("second click deletes", #ui:ListConfigs() == 0 and ui:GetAutoload() == nil)
	H.click(buttons(custom.Frame, "Export"))
	T.check("Export fills the code field", custom.Code:Get():sub(1, 6) == "MAUI1:")
	H.click(buttons(custom.Frame, "Import"))
	T.check("no crash importing", true)
	custom.Code:Set("garbage", true)
	H.click(buttons(custom.Frame, "Import"))
	T.check("a bad code only produces an error", true)
	local before = M.instanceCount
	editor:Destroy(); custom:Destroy()
	T.check("both components destroy cleanly", editor.Section.Destroyed and custom.Section.Destroyed)
end
